### ISSUE TITLE
Incorrect Conda Dependancy for vtkbone

### ISSUE THREAD

**Issue by Besler** [Numerics88/vtkbone#1]
The conda dependancies do not appear to be set correctly. The issue appeared after updating to OSX Sierra and reinstalling anaconda.

The current dependancy list is:
```>     aimio:      1.0.0-2       numerics88
>     boost:      1.60.0-py27_0           
>     curl:       7.49.0-1                
>     hdf4:       4.2.11-0                
>     hdf5:       1.8.17-1                
>     icu:        54.1-0                  
>     jpeg:       9b-0                    
>     libnetcdf:  4.4.1-0                 
>     n88util:    2.0.0-1       numerics88
>     openssl:    1.0.2k-1                
>     pip:        9.0.1-py27_1            
>     python:     2.7.13-0                
>     readline:   6.2-2                   
>     setuptools: 27.2.0-py27_0           
>     sqlite:     3.13.0-0                
>     tk:         8.5.18-0                
>     vtk:        6.3.0-py27_1            
>     vtkbone:    1.0.0-py27_1  numerics88
>     wheel:      0.29.0-py27_0           
>     zlib:       1.2.8-3
```

Below is a minimum example to recreate the issue. I am using Anaconda3 with OSX 10.12.3
```
$ conda create -n test -c numerics88 python=2 vtk vtkbone
$ source activate test
$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import vtkbone
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/babesler/anaconda3/envs/test/lib/python2.7/site-packages/vtkbone/__init__.py", line 4, in <module>
    from vtkbonePython import *
ImportError: dlopen(/Users/babesler/anaconda3/envs/test/lib/python2.7/site-packages/vtkbone/vtkbonePython.so, 2): Library not loaded: @rpath/libmfhdf.0.dylib
  Referenced from: /Users/babesler/anaconda3/envs/test/lib/libnetcdf.11.dylib
  Reason: image not found
>>> 
```

You can see that libmfhdf.0.dylib cannot be found. I managed to find a fix last night from [this post](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/c34mIs_cCrY). It goes like so:
```
$ conda create -n test2 -c numerics88 python=2.7 vtkbone
$ source activate test2
$ conda update hdf4
$ python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import vtkbone
>>> 
```

Is it possible to update the dependancy in the conda build easily? Do you think this is the issue?

**Comment by Besler** [comment]
My fix for this is fairly simple. Update the `meta.yaml` file such that the run requirement has:
```
- hdf4 >=4.2.12
```

**Comment by Besler** [comment]
I believe this issue has been resolved. Most likely, an underlying package had a poorly outlined dependancy on hdf4.

If the `meta.yaml` file is needed see: https://github.com/Besler/conda-recipes

Closing.
